-- ============================================================================
-- Monthly spending reports, generated by the home-machine Gemma pipeline
-- (tools/monthly-report.js). Unlike deal_findings/service_domains, this IS
-- personal data - one row per user per month - so it follows the normal
-- per-user RLS pattern (like expenses/subscriptions), not the shared/public
-- pattern.
-- ============================================================================
create table if not exists spending_insights (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null default auth.uid() references auth.users(id) on delete cascade,
  period        text not null,             -- 'YYYY-MM' the report covers
  report        text not null,             -- Gemma's generated natural-language report
  generated_by  text default 'gemma',
  created_at    timestamptz default now()
);
create unique index if not exists spending_insights_user_period_idx on spending_insights (user_id, period);
create index if not exists spending_insights_user_created_idx on spending_insights (user_id, created_at desc);

grant select on spending_insights to authenticated;

alter table spending_insights enable row level security;
drop policy if exists "own insights" on spending_insights;
create policy "own insights" on spending_insights
  for select using (auth.uid() = user_id);
-- No insert/update/delete policy for the client - only the home-machine
-- report script (service_role, sets user_id explicitly per user it loops
-- over) writes here, same write-boundary pattern as deal_findings.
